name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        java-package: 'jdk+fx'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        path: HMCL/build/libs
